<?php
if (!defined('_PS_VERSION_')) {
    exit;
}

class infiniteScrollPrestashop extends Module
{

    public function __construct($name = null, Context $context = null)
    {

        $this->name = 'infiniteScrollPrestashop';
        $this->tab = 'front_office_features';
        $this->version = '1.0.0';
        $this->author = 'AndrewIce77';
        $this->need_instance = 0;
        $this->bootstrap = true;

        parent::__construct();

        $this->displayName = $this->trans('Infinite Scroll for Prestashop', [], 'Modules.infiniteScrollPs.Admin');
        $this->description = $this->trans('Add automatically infinite scroll to your Prestashop', [], 'Modules.infiniteScrollPs.Admin');

        $this->ps_versions_compliancy = array('min' => '1.7.1', 'max' => '1.7.8');
    }


    public function install()
    {

        return  $this->registerHook('displayHeader') &&
                $this->registerHook('displayFooter') &&
                $this->initParams() &&
                parent::install();

    }

    public function uninstall()
    {
        Configuration::deleteByName('INFINITE_SCROLL_PS');
        return parent::uninstall(); // TODO: Change the autogenerated stub
    }

    private function initParams()
    {
        $data = [
            'btn_text' => 'Load More...',
            'btn_color' => '#000000',
            'scroll_type' => '1',
            'controllers_enabled' => 'category,manufacturer,supplier'
        ];

        return Configuration::updateValue('INFINITE_SCROLL_PS', serialize($data));
    }


    public function postProcess()
    {
        if (Tools::isSubmit('submitInfiniteScrollPs')) {

            $controllers = implode(',', Tools::getValue('controllers_enabled'));

            $data = [
                'btn_text' => Tools::getValue('btn_text'),
                'btn_color' => Tools::getValue('btn_color'),
                'scroll_type' => Tools::getValue('scroll_type'),
                'controllers_enabled' => $controllers
            ];

            Configuration::updateValue('INFINITE_SCROLL_PS', serialize($data));


            return $this->displayConfirmation($this->trans('The settings have been updated.', [], 'Admin.Notifications.Success'));
        }
        return '';
    }


    public function getContent()
    {
        return $this->postProcess() . $this->renderForm();
    }

    public function renderForm()
    {
        $fields_form = [
            'form' =>  [
                'legend' => [
                    'title'         => $this->trans('Settings', [], 'Modules.infiniteScrollPs.Admin'),
                    'icon'          => 'icon-cogs',
                ],
                'input' => [
                    [
                        'type'      => 'text',
                        'label'     => $this->trans('Text Button', [], 'Modules.infiniteScrollPs.Admin'),
                        'name'      => 'btn_text',
                        'class'     => 'fixed-width-sm',
                    ],
                    [
                        'type'      => 'color',
                        'label'     => $this->trans('Color button', [], 'Modules.infiniteScrollPs.Admin'),
                        'name'      => 'btn_color',
                        'class'     => 'fixed-width-sm',
                    ],
                    [
                        'type'      => 'select',
                        'label'     => $this->trans('Type of scroll', [], 'Modules.infiniteScrollPs.Admin'),
                        'name'      => 'scroll_type',
                        'class'     => 'fixed-width-sm',
                        'required'  => true,
                        'options'   => [
                            'query' => [
                                [
                                    'id_option' => '1',
                                    'name' => $this->trans('Automatically', [], 'Modules.infiniteScrollPs.Admin'),
                                ],
                                [
                                    'id_option' => '2',
                                    'name' => $this->trans('Manually', [], 'Modules.infiniteScrollPs.Admin'),
                                ]
                            ],
                            'id'    => 'id_option',
                            'name'  => 'name'
                        ]
                    ],
                    [
                        'type'      => 'multiselect',
                        'label'     => $this->trans('Controllers Enabled', [], 'Modules.infiniteScrollPs.Admin'),
                        'name'      => 'controllers_enabled',
                        'desc'      => $this->trans('Select the controllers where you want to enable the infinite scroll', [], 'Modules.infiniteScrollPs.Admin'),
                    ],
                ],
                'submit' => [
                    'title'     => $this->trans('Save', [], 'Admin.Actions'),
                ],
            ]
        ];

        $helper = new HelperForm();
        $helper->show_toolbar = true;
        $helper->table = $this->table;
        $helper->module = $this;
        $helper->default_form_language = $this->context->language->id;
        $helper->allow_employee_form_lang = Configuration::get('PS_BO_ALLOW_EMPLOYEE_FORM_LANG', 0);
        $helper->identifier = $this->identifier;
        $helper->submit_action = 'submitInfiniteScrollPs';
        $helper->currentIndex = $this->context->link->getAdminLink('AdminModules', false)
                                .'&configure=' . $this->name
                                .'&tab_module=' . $this->tab
                                .'&module_name=' . $this->name;
        $helper->token = Tools::getAdminTokenLite('AdminModules');
        $helper->tpl_vars = [
            'fields_value'  => $this->getParams(),
        ];

        return $helper->generateForm([$fields_form]);
    }


    private function getParams()
    {
        $params = unserialize(',', Configuration::get('INFINITE_SCROLL_PS'));
        return $params ?: [];
    }


    public function hookDisplayHeader(  )
    {
        return $this->displayInfiniteScroll();
    }

    public function hookDisplayFooter(  )
    {
        return $this->displayInfiniteScroll();
    }


    public function displayInfiniteScroll()
    {
        // CHeck controllers enabled

        // Include infinite scroll js and functionality
        return '';

    }



}